### ISSUE TITLE
Docker Compose Example

### ISSUE THREAD

**Issue by johncadengo** [selkies-project/docker-nvidia-glx-desktop#31]
For my workflow, I prefer managing my containers with docker compose. Is it possible to support a docker-compose configuration? I can show you what I wrote up to get it working on my machine. Just want to make sure it was kept up to date as updates are made.

This basically takes what example docker run you have in the readme,

```
docker run --gpus 1 -it --tmpfs /dev/shm:rw -e TZ=UTC -e SIZEW=1920 -e SIZEH=1080 -e REFRESH=60 -e DPI=96 -e CDEPTH=24 -e VIDEO_PORT=DFP -e PASSWD=mypasswd -e WEBRTC_ENCODER=nvh264enc -e BASIC_AUTH_PASSWORD=mypasswd -p 8080:8080 ghcr.io/ehfd/nvidia-glx-desktop:latest
```

And translates it for docker compose:

```
version: '3.3'
services:
  ehfd:
    tmpfs: '/dev/shm:rw'
    environment:
      - TZ=UTC
      - SIZEW=1920
      - SIZEH=1080
      - REFRESH=60
      - DPI=96
      - CDEPTH=24
      - PASSWD=mypasswd
      - WEBRTC_ENCODER=nvh264enc
      - BASIC_AUTH_PASSWORD=mypasswd
      - NOVNC_ENABLE=true
    ports:
      - '8080:8080'
    image: 'ghcr.io/ehfd/nvidia-glx-desktop:latest'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
```

**Comment by ehfd** [comment]
https://github.com/ehfd/docker-nvidia-glx-desktop/blob/main/xgl.yml
This file for Kubernetes is pretty similar to Docker compose in format. I am sure this will be a good reference for you.
I think the existing configuration will work, but please do read the file carefully and take note of new features.
Please leave a message here if you need help, or come to our [Discord](https://discord.gg/wDNGDeSW5F).

**Comment by huapox** [comment]
try this(version 2.4): https://github.com/infrastlabs/docker-headless/blob/dev/docker-compose.lite.yml

```yaml
version: '2.4'
services:
  headless:
    image: infrastlabs/docker-headless:latest
    container_name: headless
    restart: unless-stopped
    # https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck
    healthcheck:
      test: ["CMD", "bash", "-c", "supervisorctl status |grep -v 'RUNNING' && exit 1 || exit 0 "]
      interval: 5s
      timeout: 3s 
      retries: 3
      start_period: 5s
    network_mode: host
    privileged: true #xrdp-disk-mount
    shm_size: 1g
    environment:
      - VNC_OFFSET=10  #5900+10
      - L=zh_CN
      - SSH_PASS=headless
      - VNC_PASS=headless
      - VNC_PASS_RO=View123
    volumes:
      # - /_ext:/_ext
      - /opt:/opt
      - /:/mnt
```
